metrics-server:
  apiService:
    create: true
  args:
    - --secure-port=8443
    - --cert-dir=/tmp
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --kubelet-insecure-tls=true
    - --kubelet-use-node-status-port
    - --metric-resolution=15s
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 150m
      memory: 192Mi
